image: docker:git
services:
  - docker:dind
variables:
  TEST_IMAGE: $CI_REGISTRY/citygro/docker-and-compose:$CI_BUILD_REF_NAME
  RELEASE_IMAGE: $CI_REGISTRY/citygro/docker-and-compose:$CI_BUILD_REF_NAME
stages:
  - build
  - release
build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
release-image:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
